#!/bin/bash
set -e

if [[ "${IS_IGNORE_ERRORS}" == "true" ]] ; then
echo " (i) Ignore Errors: enabled"
set +e
else
echo " (i) Ignore Errors: disabled"
fi

echo
echo '#'
echo '# This System Report was generated by: https://github.com/bitrise-docker/android-ndk-lts/blob/master/system_report.sh'
echo '#  Pull Requests are welcome!'
echo '#'
echo

echo
echo "--- Bitrise CLI tool versions"
ver_line="$(bitrise --version)" ;                 echo "* bitrise: $ver_line"
ver_line="$(/root/.bitrise/tools/stepman --version)" ; echo "* stepman: $ver_line"
ver_line="$(/root/.bitrise/tools/envman --version)" ;  echo "* envman: $ver_line"

if [[ "$CI" == "false" ]] ; then
set +e
fi
ver_line="$(bitrise-bridge --version || echo 'No bitrise-bridge installed'))" ;          echo "* bitrise-bridge: $ver_line"
set -e
echo "========================================"
echo

echo
echo "=== Revision / ID ======================"
if [ -z "$BITRISE_DOCKER_REV_NUMBER_ANDROID_NDK" ] ; then
  echo " [!] No BITRISE_DOCKER_REV_NUMBER_ANDROID_NDK defined!"
  exit 1
fi
echo "* BITRISE_DOCKER_REV_NUMBER_ANDROID_NDK: $BITRISE_DOCKER_REV_NUMBER_ANDROID_NDK"
if [ -z "$BITRISE_DOCKER_REV_NUMBER_ANDROID_NDK_LTS" ] ; then
  echo " [!] No BITRISE_DOCKER_REV_NUMBER_ANDROID_NDK_LTS defined!"
  exit 1
fi
echo "* BITRISE_DOCKER_REV_NUMBER_ANDROID_NDK_LTS: $BITRISE_DOCKER_REV_NUMBER_ANDROID_NDK_LTS"
echo "========================================"
echo
echo "$ cat ${ANDROID_NDK_HOME}/source.properties"
cat "${ANDROID_NDK_HOME}/source.properties"
echo
echo "$ tree -L 2 /opt/android-ndk"
tree -L 2 /opt/android-ndk
echo
